### Initialization

In [ ]:
import numpy as np
import pandas as pd
from sbi import utils as utils

### Processing data extracted from Kruse Paper

In [2]:
# read in the data extracted from Figure 3 of the Kruse et al. 2023 paper, see:
# https://link.aps.org/doi/10.1103/PRXEnergy.2.043003
# note that we did not use the power fluctuation strength D data

tau_mean = np.loadtxt("KRUSE plot data/tau_mean.txt")
tau_min = np.loadtxt("KRUSE plot data/tau_min.txt")
tau_max = np.loadtxt("KRUSE plot data/tau_max.txt")

kappa_mean = np.loadtxt("KRUSE plot data/kappa_mean.txt")
kappa_min = np.loadtxt("KRUSE plot data/kappa_min.txt")
kappa_max = np.loadtxt("KRUSE plot data/kappa_max.txt")

q1_mean = np.loadtxt("KRUSE plot data/q1_mean.txt")
q1_min = np.loadtxt("KRUSE plot data/q1_min.txt")
q1_max = np.loadtxt("KRUSE plot data/q1_max.txt")

r_mean = np.loadtxt("KRUSE plot data/r_mean.txt")
r_min = np.loadtxt("KRUSE plot data/r_min.txt")
r_max = np.loadtxt("KRUSE plot data/r_max.txt")

In [ ]:
# create a dataframe combining the extracted data
# uses the hour of the day as the index, from 0 to 23
data = {"tau_min": tau_min, "tau_max": tau_max, "kappa_min": kappa_min, "kappa_max": kappa_max, "q1_min": q1_min, "q1_max": q1_max, "r_min": r_min, "r_max": r_max}
df = pd.DataFrame(data)
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
df.index.name = "Hour"

In [4]:
df

,tau_min,tau_max,kappa_min,kappa_max,q1_min,q1_max,r_min,r_max
Hour,,,,,,,,
0,27.148889,40.890513,128.943807,201.580781,-0.011833,-0.002708,2.941021e-06,0.000007
1,25.116573,38.844106,128.234685,185.098516,-0.011046,-0.002785,2.336882e-06,0.000007
2,24.548832,39.582388,123.591093,171.626750,-0.010121,-0.000188,5.675024e-07,0.000007
3,22.916453,34.487251,122.800647,168.523779,-0.009263,0.000708,1.095734e-07,0.000005
4,22.544542,36.580357,118.086469,168.936572,-0.007229,0.005378,-2.574343e-06,0.000005
5,24.059333,49.335368,113.040905,165.610827,-0.003868,0.008217,-4.052158e-06,0.000004
6,26.091769,60.385389,115.458428,153.870481,-0.001044,0.011199,-6.925700e-06,0.000003
7,28.604754,61.327964,108.269373,152.106685,0.000664,0.011881,-6.178524e-06,0.000002
8,28.602579,52.986755,103.906416,156.503472,-0.001076,0.009261,-4.975547e-06,0.000006
9,24.031362,46.523456,109.506227,158.882086,-0.009672,0.007650,-3.220315e-06,0.000008
10,22.758285,40.937419,118.668997,161.748009,-0.010225,0.003832,-2.062530e-06,0.000008
11,24.142610,40.732751,123.715437,162.021741,-0.009729,0.002620,-1.951107e-06,0.000006
12,23.560642,39.580395,126.683721,177.273352,-0.009513,0.001187,-1.085256e-06,0.000007
13,21.675034,35.022377,138.012125,187.626082,-0.009150,0.001844,-5.855197e-07,0.000006
14,21.099322,36.726556,140.273853,190.407200,-0.007704,0.005090,-3.023743e-06,0.000004
15,22.163311,40.863306,133.166808,183.429303,-0.004307,0.007501,-4.674269e-06,0.000002
16,24.448868,51.039455,132.535820,187.591773,-0.001136,0.009437,-6.798279e-06,0.000001
17,26.509386,58.379386,136.493936,187.626524,0.001278,0.010774,-7.141875e-06,0.000003
18,30.587836,57.423997,130.806489,189.198500,-0.006928,0.010935,-7.121255e-06,0.000007
19,26.992864,56.115580,128.222578,181.963964,-0.012131,0.010765,-6.023955e-06,0.000009
20,25.192539,46.450310,130.400454,185.293018,-0.013960,0.007724,-3.980507e-06,0.000010
21,23.631421,47.415200,130.054103,193.142271,-0.013705,0.002788,7.530889e-07,0.000010
22,25.229771,47.833852,128.260002,198.027366,-0.012633,0.002071,2.634403e-06,0.000010
23,29.854807,43.978976,135.918892,196.322583,-0.012906,-0.003998,3.832464e-06,0.000010

In [5]:
# convert the parameters from the Kruse paper to the parameters used by us

df2 = pd.DataFrame()
df2["c1_min"] = 1 / df["tau_max"]
df2["c1_max"] = 1 / df["tau_min"]
df2["c2_min"] = 1 / (df["kappa_max"] ** 2)
df2["c2_max"] = 1 / (df["kappa_min"] ** 2)
df2["p0_min"] = df["q1_min"]
df2["p0_max"] = df["q1_max"]
df2["p1_min"] = df["r_min"]
df2["p1_max"] = df["r_max"]

In [6]:
df2

,c1_min,c1_max,c2_min,c2_max,p0_min,p0_max,p1_min,p1_max
Hour,,,,,,,,
0,0.024456,0.036834,0.000025,0.000060,-0.011833,-0.002708,2.941021e-06,0.000007
1,0.025744,0.039814,0.000029,0.000061,-0.011046,-0.002785,2.336882e-06,0.000007
2,0.025264,0.040735,0.000034,0.000065,-0.010121,-0.000188,5.675024e-07,0.000007
3,0.028996,0.043637,0.000035,0.000066,-0.009263,0.000708,1.095734e-07,0.000005
4,0.027337,0.044357,0.000035,0.000072,-0.007229,0.005378,-2.574343e-06,0.000005
5,0.020269,0.041564,0.000036,0.000078,-0.003868,0.008217,-4.052158e-06,0.000004
6,0.016560,0.038326,0.000042,0.000075,-0.001044,0.011199,-6.925700e-06,0.000003
7,0.016306,0.034959,0.000043,0.000085,0.000664,0.011881,-6.178524e-06,0.000002
8,0.018873,0.034962,0.000041,0.000093,-0.001076,0.009261,-4.975547e-06,0.000006
9,0.021495,0.041612,0.000040,0.000083,-0.009672,0.007650,-3.220315e-06,0.000008
10,0.024428,0.043940,0.000038,0.000071,-0.010225,0.003832,-2.062530e-06,0.000008
11,0.024550,0.041421,0.000038,0.000065,-0.009729,0.002620,-1.951107e-06,0.000006
12,0.025265,0.042444,0.000032,0.000062,-0.009513,0.001187,-1.085256e-06,0.000007
13,0.028553,0.046136,0.000028,0.000053,-0.009150,0.001844,-5.855197e-07,0.000006
14,0.027228,0.047395,0.000028,0.000051,-0.007704,0.005090,-3.023743e-06,0.000004
15,0.024472,0.045120,0.000030,0.000056,-0.004307,0.007501,-4.674269e-06,0.000002
16,0.019593,0.040902,0.000028,0.000057,-0.001136,0.009437,-6.798279e-06,0.000001
17,0.017129,0.037722,0.000028,0.000054,0.001278,0.010774,-7.141875e-06,0.000003
18,0.017414,0.032693,0.000028,0.000058,-0.006928,0.010935,-7.121255e-06,0.000007
19,0.017820,0.037047,0.000030,0.000061,-0.012131,0.010765,-6.023955e-06,0.000009
20,0.021528,0.039694,0.000029,0.000059,-0.013960,0.007724,-3.980507e-06,0.000010
21,0.021090,0.042317,0.000027,0.000059,-0.013705,0.002788,7.530889e-07,0.000010
22,0.020906,0.039636,0.000026,0.000061,-0.012633,0.002071,2.634403e-06,0.000010
23,0.022738,0.033495,0.000026,0.000054,-0.012906,-0.003998,3.832464e-06,0.000010

In [22]:
# save dataframe to file, to be used in training
df2.to_csv("KRUSE plot data/prior_parameter_ranges.csv")

#### Appendix Table of Empirical Parameters

In [ ]:
# we create the table which is included in the thesis by rounding the values to 5 decimal places and only including the parameters c1 and c2
df3 = df2[["c1_min", "c1_max", "c2_min", "c2_max"]]
df3 = df3.round(5)
df3.to_csv("KRUSE plot data/thesis_table_parameter_ranges.csv", float_format="%.5f")